### ISSUE TITLE
Not installable via pip on Ubuntu 16.04

### ISSUE THREAD

**Issue by bontchev** [xarf/python-xarf#4]
The package cannot be installed via `pip` on Ubuntu 16.04. The command

```
sudo -H pip install python-xarf
```

produces the error

```
  Could not find a version that satisfies the requirement python-xarf (from versions: )
No matching distribution found for python-xarf
```

I managed to install the package via `easy_install`, but you really need to fix the package on `pypi`.

**Comment by FrederikP** [comment]
The name of the package on pypi is pyxarf.

```
pip install pyxarf
```

I don't know why the project name and package name are different, but this project ist quite old and I just had a closer look at it now.
