### ISSUE TITLE
Unsupported date formats

### ISSUE THREAD

**Issue by bontchev** [xarf/python-xarf#5]
According to the [documentation](https://github.com/xarf/python-xarf/blob/master/docs/xarfutil/parameters.rst),

> The given date string has to be [RFC 2822](http://tools.ietf.org/html/rfc2822.html) or [RFC 3339](http://tools.ietf.org/html/rfc3339.html) compliant.

This is simply not true. Dates like "Tue, 08 May 2018 13:30:32 -0000" (RFC 2822) are accepted but dates like "2018-05-06T21:02:41.869246Z" (RFC 3339) are _not_.

**Comment by FrederikP** [comment]
This will be fixed in version 0.1.0 as we upgraded the dependency to jsonschema.

**Comment by FrederikP** [comment]
Please try version 0.1.0 https://pypi.org/project/pyxarf/
